channels:
  - defaults
dependencies:
  - bcolz=1.2.0
  - imageio=2.3.0
  - jupyter=1.0.0
  - keras=2.2.4
  - matplotlib=3.0.2
  - opencv=3.4.2
  - pandas=0.23.4
  - pillow=5.4.1
  - python=3.6.4
  - pytorch=0.4.1
  - scikit-learn=0.20.1
  - tabulate=0.8.2
  - tensorflow=1.12.0
  - tensorflow-gpu=1.12.0
  - tqdm=4.29.1
